import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";

import { ProductProvider } from "./context/product-context";
import { EmployeeProvider } from "./context/employee-context";
import { BranchProvider } from "@/contexts/branch-context";
import { TransactionProvider } from "./context/transaction-context";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BranchProvider>
          <EmployeeProvider>
            <ProductProvider>
              <TransactionProvider>
                {children}
                <Toaster />
              </TransactionProvider>
            </ProductProvider>
          </EmployeeProvider>
        </BranchProvider>
      </body>
    </html>
  );
}
